### ISSUE TITLE
Using amp; instead of & in HTML

### ISSUE THREAD

**Issue by griffinlacek** [ebclass/prj-rev-bwfs-dasmoto#1]
Tiny thing! In HTML when using & it's best to use the HTML code & since the browser doesn't always know what & is inside of HTML. You actually do this in the body, which is excellent! Just remember it does act the same in the head too!

Check this out for more codes: http://www.html.am/html-codes/

https://github.com/ebclass/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L6
https://github.com/ebclass/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/index.html#L9

**Comment by ebclass** [comment]
Corrected, thanks for the pointer.
