### ISSUE TITLE
Targeting html in CSS

### ISSUE THREAD

**Issue by griffinlacek** [ebclass/prj-rev-bwfs-dasmoto#4]
Nothing wrong with using html to set styles for the page, but body is often used instead as it directly influences children elements. Here's a good discussion on this: https://css-tricks.com/html-vs-body-in-css/

https://github.com/ebclass/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/index.css#L2-L4

**Comment by ebclass** [comment]
I changed that to body
